### ISSUE TITLE
Unable to get satisfied records with condition

### ISSUE THREAD

**Issue by vinithanv** [CuyZ/Valinor#334]
Hi, 

Unable to get satisfied records that met the condition.

**My array is,**
$customer = [ 
    0 => [
      "customer_id" => 6628381557042
    ],
    1 => [
      "customer_id" => 6628381589810
    ],
    2 => [
      "customer_id" => 6628381622578
    ],
    3 => [
      "customer_id" => 6628381655346
    ],
    4 => [
      "customer_id" => null
    ],
  ];

**Any my validation** 

final class Customer
{
    public function __construct(
        public readonly int $customer_id,
    ) {
        //
    }
}

 $result = (new \CuyZ\Valinor\MapperBuilder)
                ->mapper()
                ->map(
                    'array<' . Customer::class . '>',
                    $customer
                );

How can i get first four record those satisfied with the condition.

Please help anyone.

**Comment by romm** [comment]
Hi @vinithanv, because the 5th row from the input contains an invalid value `null`, the whole mapping fails. You can get more insight about errors, read [documention for more information](https://valinor.cuyz.io/1.2/usage/error-handling/).

Please note that this is an intended behaviour, if any value is invalid in the whole input, the whole mapping will fail and there is no way to get any data from it.
