### ISSUE TITLE
default values in the constructor

### ISSUE THREAD

**Issue by novafree1** [CuyZ/Valinor#34]
HI

I tried to create object with default value

final class SomeClass
{
    public function __construct(private string $var='aa')
    {

    }
}

with empty input data

 (new \CuyZ\Valinor\MapperBuilder())
        ->mapper()
        ->map(
            SomeClass::class,
            []
        );

and got CannotMapObject Exception

It seems to me that in this case have to be assignment of a default value not exception. How do You Think?

**Comment by romm** [comment]
Hi @novafree1, in this particular case you are mapping to an object that has only one property, this is why you encounter this exception. If you call the `map` method with `null` as a second argument, the default value will be used and no exception will be raised.

Also note that if there are at least two parameters in your constructor, there will be no issue calling the mapper with `[]`.

I'm not worried by cases like your example, because there is no real added value using Valinor for a use case as simple as the one you described — I guess you were just toying around with the library to see how you could use it in a real project?

**Comment by novafree1** [comment]
Hi!

Thank You for Your response. You done supper useful component. I checked default values on object with several values, yes it's working fine. But I think that behavior of the component should be the same regardless of parameters count. I agree that situation with one default parameter is rare, but it can be. For example when user working with some entity and need to confirm some action. entityId and action is part of the url confirm checkbox is post parameter. If user not confirm checkbox action can not proceed. So missing agree parameter and agree parameter with 0 value should be treated the same.

**Comment by romm** [comment]
Hi @novafree1, better late than never 🙂 — #159 should fix this issue. Can you try it out on your side and give feedback?

**Comment by romm** [comment]
Fixed with #159.
