### ISSUE TITLE
Segfault during custom date time object

### ISSUE THREAD

**Issue by mairo744** [CuyZ/Valinor#352]
Hi,
     it looks like infinite loop when `AdvancedClassNameToken `try to resolve parent type `\DateInterval`. When I use custom date time object with custom date interval object everything after `CustomDateTime::diff` method goes into infinite loop. I am using valinor 1.3.0 but it was starting from version 1.1.0.

**Reproduction**:
```php

final class Request {
    public function __construct(
        public readonly CustomDateTime $time,
    ) {}
}

final class CustomDateTime extends \DateTimeImmutable
{
    /**
     * @throws Exception
     */
    public function diff($targetObject, bool $absolute = false): CustomeDateInterval 
    {
        return new CustomeDateInterval ('P1Y');
    }
}

final class CustomeDateInterval extends \DateInterval {

}


//segmentation fault
$mapper = (new MapperBuilder())->mapper();
$mapper->map(Request::class, ['time' => '']);
```

**Expected behavior**:
Valinor can map `CustomeDateInterval ` with `CustomDateTime`

**UPDATE:**

It is really because of `CustomDateTime::diff` return `CustomDateInterval`.
This implementation of `diff` method with default `DateInterval` works fine
```php
public function diff($targetObject, bool $absolute = false): \DateInterval
    {
        return new \DateInterval ('P1Y');
    }
```

**Comment by pauci** [comment]
I was able to reproduce the infinity loop with the following test:
```php
<?php

declare(strict_types=1);

namespace CuyZ\Valinor\Tests\Integration\Mapping\Object;

use CuyZ\Valinor\Mapper\MappingError;
use CuyZ\Valinor\MapperBuilder;
use CuyZ\Valinor\Tests\Integration\IntegrationTest;

final class ExtendedDateIntervalMappingTest extends IntegrationTest
{
    public function test_extended_date_interval_is_mapped_properly(): void
    {
        try {
            $result = (new MapperBuilder())
                ->mapper()
                ->map(DateInterval::class, 'P1Y2M3DT4H5M6S');
        } catch (MappingError $error) {
            $this->mappingFail($error);
        }

        self::assertSame('P1Y2M3DT4H5M6S', $result->format('P%yY%mM%dDT%hH%iM%sS'));
    }
}

class DateInterval extends \DateInterval
{
}
```

```
There was 1 error:

1) CuyZ\Valinor\Tests\Integration\Mapping\Object\ExtendedDateIntervalMappingTest::test_extended_date_interval_is_mapped_properly
Error: Xdebug has detected a possible infinite loop, and aborted your script with a stack depth of '256' frames
```
Interestingly the problem only occurs when the mapped class has a **same basename** as the class that is being extended.

So while it does not work for `class DateInterval extends \DateInterval`, it does work properly for  `CustomDateInterval extends \DateInterval` as in original @mairo744 example.

**Comment by fritz-gerneth** [comment]
Encountering the same/similar issue with `DateTimeImmutable`, respectively `Safe\DateTimeImmutable`:
```
$mapper = (new MapperBuilder())->supportDateFormats(DATE_ATOM)->mapper();
$date = $mapper->map(\Safe\DateTimeImmutable::class, '2021-01-03T02:30:00+01:00');
```

Though this also happens when using a custom class with a completely different name:
```
class MyClass extends \Safe\DateTimeImmutable {}

$mapper = (new MapperBuilder())->supportDateFormats(DATE_ATOM)->mapper();
$date = $mapper->map(MyClass::class, '2021-01-03T02:30:00+01:00');
```

Running out of memory in both instances, figure same infinite loop.

Using the built-in `DateTimeImmutable` works.

**Comment by pauci** [comment]
@fritz-gerneth I suppose that class `\Safe\DateTimeImmutable` extends `\DateTimeImmutable` so problem occurs when Valinor tries to resolve parent class of `MyClass` and subsequently the parent class of `\Safe\DateTimeImmutable`.

The problem is caused by `\CuyZ\Valinor\Type\Parser\Lexer\AliasLexer::resolveNamespaced()` which incorrently prefixes the parent class `\DateTimeImmutable` of `\Safe\DateTimeImmutable` with a namespace `\Safe` changing it to `\Safe\DateTimeImmutable` again and thus causing infinite loop.
